name: Build Site
on:
  push:
    branches: [ main ]
jobs:
  build_site:
    runs-on: ubuntu-latest
    name: Build Site
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to GH Page
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: ./